-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 15:39:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e22002182_db1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e22002182_db1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e22002182_db1` DEFAULT CHARACTER SET utf8mb4 ;
USE `e22002182_db1` ;

-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_categorie_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_categorie_cat` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_categorie_cat` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nom` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_concours_con`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_concours_con` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_concours_con` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_nom` VARCHAR(80) NOT NULL,
  `con_date_debut` DATETIME NOT NULL,
  `con_temps_candidature` DATETIME NOT NULL,
  `con_temps_select` DATETIME NOT NULL,
  `con_select` VARCHAR(80) NOT NULL,
  `con_discipline` VARCHAR(80) NOT NULL,
  `con_temps` INT NOT NULL,
  `con_image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_candidature_can`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_candidature_can` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_candidature_can` (
  `can_id` INT NOT NULL AUTO_INCREMENT,
  `can_code` CHAR(8) NOT NULL,
  `can_dossier` CHAR(20) NOT NULL,
  `can_prenom` VARCHAR(45) NOT NULL,
  `can_nom` VARCHAR(45) NOT NULL,
  `can_mail` VARCHAR(60) NOT NULL,
  `can_retenue` CHAR(1) NOT NULL,
  `can_etat` CHAR(1) NOT NULL,
  `res_id` INT(100) NOT NULL,
  `con_id` INT NOT NULL,
  PRIMARY KEY (`can_id`),
  INDEX `fk_t_candidature_can_t_categorie_cat1_idx` (`res_id` ASC) VISIBLE,
  INDEX `fk_t_candidature_can_t_concours_con1_idx` (`con_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_candidature_can_t_categorie_cat1`
    FOREIGN KEY (`res_id`)
    REFERENCES `e22002182_db1`.`t_categorie_cat` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_candidature_can_t_concours_con1`
    FOREIGN KEY (`con_id`)
    REFERENCES `e22002182_db1`.`t_concours_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_ressource_res`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_ressource_res` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_ressource_res` (
  `res_id` INT NOT NULL AUTO_INCREMENT,
  `res_nom` VARCHAR(80) NOT NULL,
  `res_description` VARCHAR(500) NOT NULL,
  `res_chemin` VARCHAR(200) NOT NULL,
  `res_type` TINYINT(5) NOT NULL,
  `can_id` INT NOT NULL,
  PRIMARY KEY (`res_id`),
  INDEX `fk_t_ressource_res_t_candidature_can_idx` (`can_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_ressource_res_t_candidature_can`
    FOREIGN KEY (`can_id`)
    REFERENCES `e22002182_db1`.`t_candidature_can` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_compte_cpt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_compte_cpt` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_compte_cpt` (
  `cpt_login` VARCHAR(120) NOT NULL,
  `cpt_mdp` CHAR(128) NOT NULL,
  `cpt_nom` VARCHAR(80) NOT NULL,
  `cpt_prenom` VARCHAR(80) NOT NULL,
  `cpt_etat` CHAR(1) NOT NULL,
  PRIMARY KEY (`cpt_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_jury_jur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_jury_jur` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_jury_jur` (
  `jur_id` INT NOT NULL AUTO_INCREMENT,
  `jur_biographie` VARCHAR(2000) NOT NULL,
  `jur_url` VARCHAR(300) NOT NULL,
  `jur_domaine_expertise` VARCHAR(80) NOT NULL,
  `cpt_login` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`jur_id`),
  INDEX `fk_t_jury_jur_t_compte_cpt1_idx` (`cpt_login` ASC) VISIBLE,
  CONSTRAINT `fk_t_jury_jur_t_compte_cpt1`
    FOREIGN KEY (`cpt_login`)
    REFERENCES `e22002182_db1`.`t_compte_cpt` (`cpt_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_fil_discussion_fil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_fil_discussion_fil` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_fil_discussion_fil` (
  `fil_id` INT NOT NULL,
  `con_id` INT NOT NULL,
  PRIMARY KEY (`fil_id`),
  INDEX `fk_t_fil_discussion_fil_t_concours_con1_idx` (`con_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_fil_discussion_fil_t_concours_con1`
    FOREIGN KEY (`con_id`)
    REFERENCES `e22002182_db1`.`t_concours_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_message_mes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_message_mes` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_message_mes` (
  `mes_id` INT NOT NULL,
  `mes_texte` VARCHAR(600) NOT NULL,
  `jur_id` INT NOT NULL,
  `fil_id` INT NOT NULL,
  `mes_etat` CHAR(1) NOT NULL,
  `mes_date` DATETIME NOT NULL,
  PRIMARY KEY (`mes_id`),
  INDEX `fk_t_message_mes_t_jury_jur1_idx` (`jur_id` ASC) VISIBLE,
  INDEX `fk_t_message_mes_t_fil_discussion_fil1_idx` (`fil_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_message_mes_t_jury_jur1`
    FOREIGN KEY (`jur_id`)
    REFERENCES `e22002182_db1`.`t_jury_jur` (`jur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_message_mes_t_fil_discussion_fil1`
    FOREIGN KEY (`fil_id`)
    REFERENCES `e22002182_db1`.`t_fil_discussion_fil` (`fil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_administrateur_adm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_administrateur_adm` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_administrateur_adm` (
  `adm_id` INT NOT NULL AUTO_INCREMENT,
  `adm_etat` CHAR(1) NOT NULL,
  `cpt_login` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`adm_id`),
  INDEX `fk_t_administrateur_adm_t_compte_cpt1_idx` (`cpt_login` ASC) VISIBLE,
  CONSTRAINT `fk_t_administrateur_adm_t_compte_cpt1`
    FOREIGN KEY (`cpt_login`)
    REFERENCES `e22002182_db1`.`t_compte_cpt` (`cpt_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_actualite_act`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_actualite_act` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_actualite_act` (
  `act_id` INT NOT NULL,
  `act_etat` CHAR(1) NOT NULL,
  `act_description` VARCHAR(1000) NOT NULL,
  `act_titre` VARCHAR(80) NOT NULL,
  `act_date` DATETIME NOT NULL,
  `con_id` INT NOT NULL,
  `adm_id` INT NOT NULL,
  PRIMARY KEY (`act_id`),
  INDEX `fk_t_actualite_act_t_concours_con1_idx` (`con_id` ASC) VISIBLE,
  INDEX `fk_t_actualite_act_t_administrateur_adm1_idx` (`adm_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_actualite_act_t_concours_con1`
    FOREIGN KEY (`con_id`)
    REFERENCES `e22002182_db1`.`t_concours_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_actualite_act_t_administrateur_adm1`
    FOREIGN KEY (`adm_id`)
    REFERENCES `e22002182_db1`.`t_administrateur_adm` (`adm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_choix_cho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_choix_cho` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_choix_cho` (
  `con_id` INT NOT NULL,
  `cat_id` INT NOT NULL,
  PRIMARY KEY (`con_id`, `cat_id`),
  INDEX `fk_t_concours_con_has_t_categorie_cat_t_categorie_cat1_idx` (`cat_id` ASC) VISIBLE,
  INDEX `fk_t_concours_con_has_t_categorie_cat_t_concours_con1_idx` (`con_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_concours_con_has_t_categorie_cat_t_concours_con1`
    FOREIGN KEY (`con_id`)
    REFERENCES `e22002182_db1`.`t_concours_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_concours_con_has_t_categorie_cat_t_categorie_cat1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `e22002182_db1`.`t_categorie_cat` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_note_not`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_note_not` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_note_not` (
  `can_id` INT NOT NULL,
  `jur_id` INT NOT NULL,
  `not_note` TINYINT NOT NULL,
  PRIMARY KEY (`can_id`, `jur_id`),
  INDEX `fk_t_candidature_can_has_t_jury_jur_t_jury_jur1_idx` (`jur_id` ASC) VISIBLE,
  INDEX `fk_t_candidature_can_has_t_jury_jur_t_candidature_can1_idx` (`can_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_candidature_can_has_t_jury_jur_t_candidature_can1`
    FOREIGN KEY (`can_id`)
    REFERENCES `e22002182_db1`.`t_candidature_can` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_candidature_can_has_t_jury_jur_t_jury_jur1`
    FOREIGN KEY (`jur_id`)
    REFERENCES `e22002182_db1`.`t_jury_jur` (`jur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22002182_db1`.`t_concours_con_has_t_jury_jur2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e22002182_db1`.`t_concours_con_has_t_jury_jur2` ;

CREATE TABLE IF NOT EXISTS `e22002182_db1`.`t_concours_con_has_t_jury_jur2` (
  `con_id` INT NOT NULL,
  `jur_id` INT NOT NULL,
  PRIMARY KEY (`con_id`, `jur_id`),
  INDEX `fk_t_concours_con_has_t_jury_jur2_t_jury_jur1_idx` (`jur_id` ASC) VISIBLE,
  INDEX `fk_t_concours_con_has_t_jury_jur2_t_concours_con1_idx` (`con_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_concours_con_has_t_jury_jur2_t_concours_con1`
    FOREIGN KEY (`con_id`)
    REFERENCES `e22002182_db1`.`t_concours_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_concours_con_has_t_jury_jur2_t_jury_jur1`
    FOREIGN KEY (`jur_id`)
    REFERENCES `e22002182_db1`.`t_jury_jur` (`jur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
